media: dwc: dw-csi-plat: fix potential uninitialized variable use
In probe, if CONFIG_OF is enable but device struct of_node has not been
set, pdata will be used uninitialised:

../drivers/media/platform/dwc/dw-csi-plat.c:497:37: error: variable 'pdata' is uninitialized when used here [-Werror,-Wuninitialized]
                 csi->phy = devm_phy_get(dev, phys[pdata->id].name);
                                                   ^~~~~
../drivers/media/platform/dwc/dw-csi-plat.c:432:29: note: initialize the variable 'pdata' to silence this warning
         struct dw_csih_pdata *pdata;
                                    ^
                                     = NULL
Check if pdata is NULL & if so abort.

CC: Eugen Hristev <eugen.hristev@microchip.com>
Signed-off-by: Conor Dooley <conor.dooley@microchip.com>
Reviewed-by: Eugen Hristev <eugen.hristev@microchip.com>
Signed-off-by: Isaac True <isaac.true@canonical.com>