gpio: gw-pld: remove unused variable
Clang complains:
../drivers/gpio/gpio-gw-pld.c:74:22: error: unused variable 'np' [-Werror,-Wunused-variable]
        struct device_node *np = dev->of_node;
                            ^
Remove the variable

Fixes: 6d8e9348287a ("gpio: Get rid of duplicate of_node assignment in the drivers")
Signed-off-by: Conor Dooley <conor.dooley@microchip.com>
Signed-off-by: Isaac True <isaac.true@canonical.com>